import { Pharmacy } from "../@types"

const data: Pharmacy[] = [
    {
        id: 1,
        name: "Pharmacie Smaali",
        address: "63 Rue la participation, Casablanca",
        latitude: 33.6021776,
        longitude: -7.5796962,
        distance: 0.3,
        images: [
            "https://placeimg.com/640/480/any",
            "https://placeimg.com/640/480/any",
        ],
        openingHours: "8:00 AM",
        closingHours: "8:00 PM",
        phone: "+212 522 22 22 22",
        email: "contact.smaali@pharmacy.ma",
        services: ["Vaccination", "Delivery", "Home Visit", "Prescription"],
        onGuard: true,
        onGuardDays: [new Date("2020-12-01"), new Date("2020-12-31")],
        reviews: [
            {
                id: 1,
                pharmacyId: 1,
                userId: 1,
                rating: 4,
                comment: "Great pharmacy, I recommend it",
                date: "2020-12-01",
            },
        ],
    },
    {
        id: 2,
        name: "Pharmacie La solidarité التضامن",
        address: "JC39+344, Casablanca",
        latitude: 33.6026381,
        longitude: -7.5821814,
        distance: 0.3,
        images: [
            "https://placeimg.com/640/480/any",
            "https://placeimg.com/640/480/any",
        ],
        openingHours: "8:00 AM",
        closingHours: "8:00 PM",
        phone: "+212 522 22 22 22",
        email: "contact.solidarité@pharmacy.ma",
        services: ["Vaccination", "Delivery", "Home Visit", "Prescription"],
        onGuard: true,
        onGuardDays: [new Date("2020-12-01"), new Date("2020-12-31")],
        reviews: [
            {
                id: 1,
                pharmacyId: 1,
                userId: 1,
                rating: 4,
                comment: "Great pharmacy, I recommend it",
                date: "2020-12-01",
            },
        ],
    },
    {
        id: 3,
        name: "pharmacie Sourzac Roches noires",
        address: "70 Rue Augustin Sourzac, Casablanca",
        latitude: 33.59975849999999,
        longitude: -7.5809605,
        distance: 0.3,
        images: [
            "https://placeimg.com/640/480/any",
            "https://placeimg.com/640/480/any",
        ],
        openingHours: "8:00 AM",
        closingHours: "8:00 PM",
        phone: "+212 522 22 22 22",
        email: "contact.sourzac@pharmacy.ma",
        services: ["Vaccination", "Delivery", "Home Visit", "Prescription"],
        onGuard: false,
        onGuardDays: null,
        reviews: [
            {
                id: 1,
                pharmacyId: 1,
                userId: 1,
                rating: 4,
                comment: "Great pharmacy, I recommend it",
                date: "2020-12-01",
            },
        ],
    },

    {
        id: 4,
        name: "Phramacie des Acacias",
        address: "HCXC+XV4, Boulevard Batli Mohamed Ben Mekki, Casablanca",
        latitude: 33.5998937,
        longitude: -7.577812000000001,
        distance: 0.3,
        images: [
            "https://placeimg.com/640/480/any",
            "https://placeimg.com/640/480/any",
        ],
        openingHours: "8:00 AM",
        closingHours: "8:00 PM",
        phone: "+212 522 22 22 22",
        email: "contact.solidarité@pharmacy.ma",
        services: ["Vaccination", "Delivery", "Home Visit", "Prescription"],
        onGuard: true,
        onGuardDays: [new Date("2020-12-01"), new Date("2020-12-31")],
        reviews: [
            {
                id: 1,
                pharmacyId: 1,
                userId: 1,
                rating: 4,
                comment: "Great pharmacy, I recommend it",
                date: "2020-12-01",
            },
        ],
    },
    {
        id: 5,
        name: "Pharmacie Belaous Laïla",
        address: "37 rue Al Bahalil 20290, Casablanca",
        latitude: 33.598445,
        longitude: -7.585731999999999,
        distance: 0.3,
        images: [
            "https://placeimg.com/640/480/any",
            "https://placeimg.com/640/480/any",
        ],
        openingHours: "8:00 AM",
        closingHours: "8:00 PM",
        phone: "+212 522 22 22 22",
        email: "contact.belous@pharmacy.ma",
        services: ["Vaccination", "Delivery", "Home Visit", "Prescription"],
        onGuard: false,
        onGuardDays: null,
        reviews: [
            {
                id: 1,
                pharmacyId: 1,
                userId: 1,
                rating: 4,
                comment: "Great pharmacy, I recommend it",
                date: "2020-12-01",
            },
        ],
    },
]

export default data
