import { Pharmacy } from "../@types"

const data: Pharmacy[] = [
    {
        id: 1,
        name: "ABC Pharmacy",
        address: "123 Main St",
        longitude: -74.0059,
        latitude: 40.7128,
        distance: 2.5,
        images: [
            "https://placeimg.com/640/480/any",
            "https://placeimg.com/640/480/any",
        ],
        stratHours: "9:00 AM",
        endHours: "6:00 PM",
        phone: "555-1234",
        email: "info@abcpharmacy.com",
        services: ["Flu Shots", "Prescription Refills"],
        onGuard: true,
        onGuardDays: ["Monday", "Wednesday", "Friday"],
        reviews: [
            {
                id: 1,
                pharmacyId: 1,
                userId: 1,
                rating: 4,
                comment: "Great service!",
                date: "2022-03-01",
            },
            {
                id: 2,
                pharmacyId: 1,
                userId: 2,
                rating: 3,
                comment: "Average experience",
                date: "2022-02-15",
            },
        ],
    },
    {
        id: 2,
        name: "XYZ Pharmacy",
        address: "456 Park Ave",
        longitude: -74.006,
        latitude: 40.7129,
        distance: 1.8,
        images: ["https://placeimg.com/640/480/any"],
        stratHours: "10:00 AM",
        endHours: "7:00 PM",
        phone: "555-5678",
        email: "info@xyzpharmacy.com",
        services: ["Vaccinations", "OTC Medications"],
        onGuard: false,
        onGuardDays: [],
        reviews: [
            {
                id: 3,
                pharmacyId: 2,
                userId: 3,
                rating: 5,
                comment: "Best pharmacy in town!",
                date: "2022-02-28",
            },
            {
                id: 4,
                pharmacyId: 2,
                userId: 4,
                rating: 2,
                comment: "Terrible customer service",
                date: "2022-02-10",
            },
        ],
    },
    {
        id: 3,
        name: "PQR Pharmacy",
        address: "789 Broadway",
        longitude: -74.0061,
        latitude: 40.713,
        distance: 3.2,
        images: ["https://placeimg.com/640/480/any"],
        stratHours: "8:00 AM",
        endHours: "5:00 PM",
        phone: "555-9012",
        email: "info@pqrpharmacy.com",
        services: ["Home Delivery", "Compounding"],
        onGuard: true,
        onGuardDays: ["Tuesday", "Thursday"],
        reviews: [
            {
                id: 5,
                pharmacyId: 3,
                userId: 5,
                rating: 4,
                comment: "Good selection of products",
                date: "2022-03-10",
            },
            {
                id: 6,
                pharmacyId: 3,
                userId: 6,
                rating: 1,
                comment: "Avoid this place",
                date: "2022-02-20",
            },
        ],
    },
]

export default data
